---
include:
  - board: xiao_ble
    shield: skeletyl_dongle
  - board: nice_nano
    shield: skeletyl_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano
    shield: skeletyl_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano
    shield: settings_reset
  - board: xiao_ble
    shield: settings_reset
